---
name: Test Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Testing-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setting up python
        uses: actions/setup-python@v2
        with:
          python-version: "3.9"
      - name: Upgrading pip
        run: |
          python -m pip install --upgrade pip
      - name: Installing dependencies
        run: |
          pip3 install -r requirements.txt
      - run: All dependencies are now installed
      - name: Checking Dependencies
        run: pip3 freeze
