---
name: Test Actions

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  Testing-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v2
      - name: Setting up python
        uses: actions/setup-python@v2
        with:
          python-version: 3.8.5
      - name: Installing dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - run: echo "All dependencies are now installed 🙌🙌"
      - name: Checking Dependencies
        run: pip3 freeze
